{
    "name": "Coffee Management",
    "version": "1.1.0",
    "author": "Application Development Team",
    "category": "Manufacturing/Manufacturing",
    "summary": "End-to-end Coffee Supply Chain Management.",
    "description": """
Robust coffee supply chain management system with full integration to Inventory, Sales, and Manufacturing.
Automates arrivals, grading, weight management, contracts, manufacturing, and delivery with full audit trail and traceability.
    """,
    "depends": [
        "stock",
        "mrp",
        "purchase",
        "sale",
        "product",
        "contacts",
        "account",
        "mail",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/coffee_data.xml",
        "views/product_template_views.xml",
        "views/product_views.xml",
        "views/coffee_arrival_views.xml",
        "views/coffee_quality_views.xml",
        "views/coffee_weight_views.xml",
        "views/coffee_weight_log_views.xml",
        "views/coffee_stock_receiving_views.xml",
        "views/coffee_stock_issue_views.xml",
        "views/coffee_contract_views.xml",
        "views/coffee_classification_views.xml",
        "views/coffee_location_views.xml",
        "views/ecx_coffee_products_views.xml",
        "views/report_views.xml",
        "views/report_analytics_views.xml",
        "views/menuitems.xml",
        "reports/coffee_reports.xml",
        "reports/coffee_report_templates.xml",
    ],
    "license": "LGPL-3",
    "installable": True,
    "application": True,
    'icon': 'coffee_management\static\img\icon.gif',
}